# This is a basic workflow that is manually triggered

name: GenerateCNIP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:
  schedule:
    - cron: '30 19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node and NPM
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      
      - name: Initialization environment
        run: sudo apt-get install -y git openssh-client ipcalc grep
      
      - name: Generate
        run: |
          rm *.txt *.rsc 
          bash ./scripts/generate.sh
          bash ./scripts/generate_ros.sh

      - name: Check CN ip list size
        run: |
          if [[ $(wc -l < ./address-list.rsc | xargs) < 3000 || $(wc -l < ./address-list.ipv6.rsc | xargs) < 1000 ]]; then
          echo "The size of ip list is not in the right range!"
          exit 1
          fi

      - name: Check current github event and ref
        run: |
          echo "The current github event is ${{github.event_name}}, git branch is ${{github.ref}}"

      - name: Checkout ip-lists branch
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/master'
        with:
          ref: ip-lists
          path: ip-lists

      - name: CheckServiceStatus
        run: |
          curl https://$MINIO_ENDPOINT/${MINIO_BUCKET}/public/status

      - name: Upload
        if: github.ref == 'refs/heads/master'
        run: |
          rm -rf ip-lists/ros || true
          mkdir ip-lists/ros || true
          mv ./*.rsc ip-lists/ros/
          cd ip-lists
          md5sum ./ros/address-list.rsc | awk '{print $1}' > ./ros/CNIPv4Md5
          md5sum ./ros/address-list.ipv6.rsc | awk '{print $1}' > ./ros/CNIPv6Md5
          if [[ $(git status .) != *"nothing to commit"* ]]; then
            git config user.name GitHub Actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "update $(date +%Y-%m-%d)"
            git push -q

            bash ../scripts/minio_upload.sh $PWD/ros/address-list.rsc public/address-list.rsc
            bash ../scripts/minio_upload.sh $PWD/ros/address-list.ipv6.rsc public/address-list.ipv6.rsc
            bash ../scripts/minio_upload.sh $PWD/ros/CNIPv4Md5 public/CNIPv4Md5
            bash ../scripts/minio_upload.sh $PWD/ros/CNIPv6Md5 public/CNIPv6Md5
          fi


        env:
          MINIO_BUCKET: ${{secrets.MINIO_OSS_BUCKET}}
          MINIO_KEY: ${{secrets.MINIO_USER}}
          MINIO_SECRET: ${{secrets.MINIO_SECRET}}
          MINIO_ENDPOINT: ${{secrets.MINIO_ENDPOINT}}
